\# Fixed compile error with 1.16.1
../nginx-rtmp-module/ngx_rtmp_eval.c: In function ‘ngx_rtmp_eval’:
../nginx-rtmp-module/ngx_rtmp_eval.c:160:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
                 switch (c) {
                 ^~~~~~
../nginx-rtmp-module/ngx_rtmp_eval.c:170:13: note: here
             case ESCAPE:
             ^~~~
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g   -I src/core -I src/event -I src/event/modules -I src/os/unix -I ../nginx-rtmp-module -I objs -I src/http                                                          -I src/http/modules \
        -o objs/addon/nginx-rtmp-module/ngx_rtmp_codec_module.o \
        ../nginx-rtmp-module/ngx_rtmp_codec_module.c
cc1: all warnings being treated as errors
make[1]: *** [objs/Makefile:1349: objs/addon/nginx-rtmp-module/ngx_rtmp_eval.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/root/build/nginx-1.16.1'
make: *** [Makefile:8: build] Error 2